# Demo dataset for local trials (docker-compose.yml sets SEED_DEMO=1).
# Loaded from db/seeds.rb only when SEED_DEMO=1. Idempotent: every record is
# found-or-created, and the trade history is only generated once per trace.
#
# Trades go through the same code path as the MetaTrader clients: the copy
# (master) terminal's JSON is fed to Message::V3::MetaCopy (what
# POST /api/v3/copy/post/orders/... does) and each slave terminal's feedback
# to Message::V3::MetaSlave (POST /api/v3/slave/post/update/...). No network
# is involved; Stripe is never called (invoices are created directly).
#
# Logins (local trial only):
#   admin: SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD (admin@example.com / password123)
#   demo customer: SEED_DEMO_EMAIL / SEED_DEMO_PASSWORD (demo@example.com / password123)
module DemoSeed
  module_function

  EXPERT = 'imentore_copy'.freeze
  VERSION = '3_00_02'.freeze
  BROKER = 'demo-broker'.freeze
  COPY_ACCOUNT = '10100'.freeze
  SLAVE_ACCOUNTS = %w[20100 20200].freeze
  TICKET_BASE = 900_000_000

  # symbol, type (0 buy / 1 sell), lots, open, close (nil = still open), profit, days ago opened, hours held
  TRADES = [
    ['EURUSD', 0, '0.10', '1.08420', '1.08710', 29.00, 29, 6],
    ['GBPUSD', 1, '0.10', '1.27150', '1.26880', 27.00, 27, 3],
    ['XAUUSD', 0, '0.05', '2331.40', '2318.90', -62.50, 25, 9],
    ['US500',  0, '0.50', '5210.5',  '5236.0',  12.75, 23, 20],
    ['EURUSD', 1, '0.20', '1.08990', '1.09110', -24.00, 20, 4],
    ['XAUUSD', 1, '0.05', '2352.10', '2339.60', 62.50, 17, 7],
    ['GBPUSD', 0, '0.15', '1.26540', '1.26910', 55.50, 14, 26],
    ['US500',  1, '0.50', '5288.0',  '5301.5',  -6.75, 11, 5],
    ['EURUSD', 0, '0.10', '1.08650', '1.08930', 28.00, 8, 30],
    ['XAUUSD', 0, '0.05', '2340.00', '2361.80', 109.00, 5, 12],
    ['GBPUSD', 1, '0.10', '1.27400', nil, -8.00, 2, nil],
    ['EURUSD', 0, '0.10', '1.08810', nil, 14.00, 1, nil],
    ['US500',  0, '0.50', '5318.25', nil, 6.25, 0, nil]
  ].freeze

  def run(store:, payment:, admin:)
    plan = store.plan
    customer_plan = CustomerPlan.find_or_create_by!(store: store, name: 'Demo Copy Plan') do |cp|
      cp.kind = :fixed
      cp.charge_recurrence = :monthly
      cp.amount = 49.90
      cp.due_at_dates = 5
      cp.payment = payment
      cp.active_at = Time.current
    end

    trace = Trace.find_by(name_id: '20001', store_id: store.id) || Trace.create!(
      name: 'Demo Signal', name_id: '20001', kind: :copy, active_at: Time.current, store_id: store.id,
      stores: [store], customer_plans: [customer_plan], contract_volume_max: 2, take_profit_limit: 2,
      instrument_control: false, capital_recomendation: '1000',
      desc_contract: 'Demo portfolio generated by db/seeds/demo.rb'
    )

    demo = demo_customer(store, customer_plan)
    server = AccountServer.find_or_create_by!(name: BROKER)

    copy = account(store, admin, server, COPY_ACCOUNT, :copy, trace)
    slaves = SLAVE_ACCOUNTS.map { |name| account(store, demo, server, name, :slave, trace) }

    generate_trades(trace, copy, slaves) unless Order.where(trace: trace).exists?
    invoices(store, payment, demo, customer_plan, trace, slaves.first)

    puts "Demo data ready: #{demo.email} / trace ##{trace.id} #{trace.name} / " \
         "#{Transaction.where(trace: trace).count} master trades, " \
         "#{TransactionSlave.where(trace_id: trace.id).count} slave trades"
    { trace: trace, copy: copy, slaves: slaves, customer: demo, plan: plan }
  end

  def demo_customer(store, customer_plan)
    email = ENV.fetch('SEED_DEMO_EMAIL', 'demo@example.com')
    user = User.find_by(email: email, store: store)
    customer = user&.userable
    unless customer
      customer = Customer.new(name: 'Demo Customer', role: 'customer', role_control: 'user', active_at: Time.current)
      customer.build_user(email: email, password: ENV.fetch('SEED_DEMO_PASSWORD', 'password123'), store: store)
      customer.save!
    end
    customer.customer_plans << customer_plan unless customer.customer_plans.include?(customer_plan)
    customer
  end

  def account(store, customer, server, name, kind, trace)
    Account.find_by(name: name, store: store, account_server: server, kind: kind) || Account.create!(
      name: name, kind: kind, store: store, customer: customer, account_server: server, state: :enable,
      meta_mode: :demo, meta_margin_mode: :hedging, contract_volume: '1', trace_ids: [trace.id]
    )
  end

  def mt5_time(time)
    time.utc.strftime('%Y.%m.%d %H:%M:%S')
  end

  def request_url(kind, account)
    "http://localhost/api/v3/#{kind}/post/#{kind == 'copy' ? 'orders' : 'update'}/#{EXPERT}/#{VERSION}/#{BROKER}/#{account.name}/HEDGING"
  end

  def rows
    now = Time.current.change(min: 0, sec: 0)
    TRADES.each_with_index.map do |(symbol, type, lot, open, close, profit, days, hours), i|
      open_at = now - days.days - (i % 5 + 1).hours
      { ticket: TICKET_BASE + i + 1, symbol: symbol, type: type, lot: lot, open: open, close: close,
        profit: profit, open_at: open_at, close_at: close && (open_at + hours.hours) }
    end
  end

  def copy_json(row, closed)
    now = mt5_time(Time.current)
    {
      'symbol' => row[:symbol], 'ticketMaster' => row[:ticket], 'ticketSlave' => -1, 'ticketDeal' => row[:ticket] + 1_000_000,
      'positionID' => row[:ticket], 'type' => row[:type], 'entry' => closed ? 1 : 0, 'volume' => row[:lot],
      'priceOpen' => row[:open], 'priceClose' => closed ? row[:close] : 0, 'profit' => row[:profit].to_s,
      'stopLoss' => 0, 'takeProfit' => 0, 'mae' => 0, 'mfe' => 0, 'commission' => 0, 'fee' => 0, 'swap' => 0,
      'magicNumber' => 0, 'comment' => '', 'state' => closed ? 'closed' : 'opened',
      'openAt' => mt5_time(row[:open_at]), 'closeAt' => closed ? mt5_time(row[:close_at]) : nil,
      'timeGMT' => now, 'timeTrader' => now, 'timeZone' => 0, 'symbolDigits' => 5
    }.compact
  end

  def post_copy(copy, payload)
    message = Message::V3::MetaCopy.create!(
      content: payload.to_json, account: copy, store: copy.store, content_at: Time.current,
      request_url: request_url('copy', copy),
      params: { 'expert_name' => EXPERT, 'expert_version' => VERSION, 'account_server_name' => BROKER,
                'account_id' => copy.name, 'account_mode' => 'HEDGING' }.to_json
    )
    message.execute
    message.execute_conciliated
  end

  def post_slave(slave, payload)
    message = Message::V3::MetaSlave.create!(
      content: payload.to_json, account: slave, store: slave.store, content_at: Time.current,
      request_url: request_url('slave', slave),
      params: { 'expert_name' => 'imentore_slave', 'expert_version' => VERSION, 'account_server_name' => BROKER,
                'account_id' => slave.name, 'account_mode' => 'HEDGING' }.to_s
    )
    message.execute
  end

  def generate_trades(trace, copy, slaves)
    all = rows
    # 1. The copy terminal reports every position as open -> orders, master
    #    transactions and one pending TransactionSlave per slave account.
    post_copy(copy, 'PositionOrders' => all.map { |r| copy_json(r, false) })

    # 2. Each slave terminal confirms it opened its copy (metaState OPEN).
    slave_ticket = TICKET_BASE + 500_000
    feedback = TransactionSlave.where(trace_id: trace.id, account: slaves).order(:id).filter_map do |ts|
      row = all.detect { |r| r[:ticket] == ts.ticket_master.to_i }
      next unless row

      slave_ticket += 1
      base = copy_json(row, false).merge('ticketSlave' => slave_ticket, 'positionID' => slave_ticket,
                                         'ticketDeal' => slave_ticket, 'comment' => ts.comment, 'profit' => '0')
      post_slave(ts.account, base.merge('metaState' => 'OPEN'))
      [ts, row, base]
    end

    # 3. The copy terminal sends its history: closed trades leave the open
    #    list, which closes the master and flags its slave copies for removal.
    closed, open = all.partition { |r| r[:close] }
    post_copy(copy, 'PositionOrders' => open.map { |r| copy_json(r, false) },
                    'HistoryOrders' => closed.map { |r| copy_json(r, true) })

    # 4. Each slave terminal closes its copy and reports the result (lot ratio 1:1).
    feedback.each do |ts, row, base|
      next unless row[:close]

      post_slave(ts.account, base.merge('metaState' => 'CLOSED', 'priceClose' => row[:close],
                                        'profit' => (row[:profit] * 0.98).round(2).to_s,
                                        'closeAt' => mt5_time(row[:close_at])))
    end

    # Seeding happens "now"; backdate timestamps so history spreads over the month.
    all.each do |r|
      finished = r[:close_at] || r[:open_at]
      Order.where(trace: trace, content_id: r[:ticket]).update_all(created_at: r[:open_at], updated_at: finished)
      Transaction.where(ticket: r[:ticket]).update_all(created_at: r[:open_at], updated_at: finished)
      slaves_rel = TransactionSlave.where(ticket_master: r[:ticket])
      slaves_rel.update_all(created_at: r[:open_at], updated_at: finished)
      slaves_rel.where.not(closed_at: nil).update_all(closed_at: r[:close_at] + 2.seconds) if r[:close_at]
    end
  end

  def invoices(store, payment, customer, customer_plan, trace, account)
    [[2, :paid], [1, :to_paid]].each do |months_ago, state|
      month = months_ago.months.ago
      name = "#{customer.id}-#{month.strftime('%Y-%m')}"
      next if customer.invoices.exists?(name: name)

      invoice = customer.invoices.create!(name: name, store: store, payment: payment, kind: :client, state: state,
                                          amount: customer_plan.amount, due_at: month.end_of_month + customer_plan.due_at_dates.to_i.days)
      invoice.items.create!(handle: 'plan', description: "#{customer_plan.name} - #{trace.name} (#{month.strftime('%b %Y')})",
                            amount: customer_plan.amount, account: account, trace: trace)
    end
  end
end
