require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

# RSpec.describe Finances::EntriesController, type: :controller do
RSpec.describe API::V1::Orders do

  before(:context) do
    @store = create(:store)
    @trace = create(:trace, :second, store: @store)
    post '/api/v1/orders', params: {"message_id"=>"720371712",
    "message"=>"UsdJpy sell now @ 105.25\nSl @ 105.65\nTp1 @ 105.05\nTp2 @ 104.65",
    "name"=>"Perucchi Inc",
    "name_id"=>"-340961920"}
    #, session: valid_session
  end

  # This should return the minimal set of attributes required to create a valid
  # Finances::Entry. As you add validations to Finances::Entry, be sure to
  # adjust the attributes here as well.

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Finances::EntriesController. Be sure to keep this updated too.

  describe API::V1::Traces do
    context 'POST /api/v*/orders' do
      it 'save a telegram trace message' do
        
        # expect(response).to be_success
        expect(response.status).to eq(201)
        # binding.pry
        expect(JSON.parse(response.body)).to be == {"id"=>1, "message_id"=>"720371712", "message"=>"UsdJpy sell now @ 105.25\nSl @ 105.65\nTp1 @ 105.05\nTp2 @ 104.65", "symbol"=>"USDJPY", "trace"=>"Perucchi Inc"}
      end
      it 'verify lot information' do
        @trace.update(take_profit: 'normal')
        get '/api/v2/orders/720371712'
        expect(JSON.parse(response.body)['lots']).to eq([0.05])

        @trace.update(take_profit: 'Agressive')
        get '/api/v2/orders/720371712'
        expect(JSON.parse(response.body)['lots']).to eq([0.03, 0.02])

        @trace.update(take_profit: 'Superagressive')
        get '/api/v2/orders/720371712'
        expect(JSON.parse(response.body)['lots']).to eq([0.03, 0.02])
      end
    end

    context 'GET /api/v1/stores' do
      it 'return all sign to execute' do
        get '/api/v1/stores'
        # expect(response).to be_success
        expect(response.status).to eq(200)
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['message_id']).to eq('720371712')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['type']).to eq('sell')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['symbol']).to eq('USDJPY')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['price_request']).to eq('105.25')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['SL']).to eq('105.65')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['TP']).to eq(['105.05'])
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['lots']).to eq([0.05])
      end
    end

    context 'GET /api/v1/orders/720371712' do
      it 'get information of message id' do
        get '/api/v1/orders/720371712'
        expect(JSON.parse(response.body)['id']).to eq(1)
        expect(JSON.parse(response.body)['message_id']).to eq('720371712')
        expect(JSON.parse(response.body)['message'].tr("\n", " ")).to be == 'UsdJpy sell now @ 105.25 Sl @ 105.65 Tp1 @ 105.05 Tp2 @ 104.65'
        expect(JSON.parse(response.body)['symbol']).to eq('USDJPY')
      end
    end

    context 'POST /api/v1/orders/transaction' do
      it 'save executed order metatrader information' do
        post '/api/v1/orders/transaction', params:{
          "chat_id"=>"2",
          "message_id"=>"720371712",
          "provider"=>"2",
          "provider_name"=>"Perucchi Inc",
          "symbol"=>"USDJPY",
          "action"=>"EXECUTION",
          "kind"=>"1",
          "price_request"=>"105.25",
          "price_open"=>"105.493",
          "stop_loss"=>"105.65",
          "take_profit"=>"105.05",
          "comment"=>"Perucchi Inc",
          "magic"=>"123456",
          "ticket"=>"363873673",
          "open_at"=>"2020.10.21 01:18:09"
        }
        expect(JSON.parse(response.body)['state']).to eq('executed')
        expect(JSON.parse(response.body)['ticket']).to eq('363873673')
        expect(JSON.parse(response.body)['action']).to eq('EXECUTION')
        expect(JSON.parse(response.body)['kind']).to eq('1')
        expect(JSON.parse(response.body)['symbol']).to eq('USDJPY')
        expect(JSON.parse(response.body)['price_request']).to eq('105.25')
        expect(JSON.parse(response.body)['price_open']).to eq('105.493')
        expect(JSON.parse(response.body)['stop_loss']).to eq('105.65')
        expect(JSON.parse(response.body)['take_profit']).to eq('105.05')
        expect(JSON.parse(response.body)['comment']).to eq('Perucchi Inc')
        expect(JSON.parse(response.body)['magic']).to eq('123456')
        expect(JSON.parse(response.body)['ticket']).to eq('363873673')
        expect(JSON.parse(response.body)['open_at']).to eq('2020-10-21T01:18:09.000Z')

      end
    end
    context 'POST /api/v1/orders/transaction' do
      it 'Error transaction from metatrader order' do
        post '/api/v1/orders/transaction', params:{
          'chat_id': 1, 'message_id': '720371712', 'provider': 1, 'provider_name': 'Perucchi Inc', 'symbol': 'USDJPY', 'action': 'EXECUTION', 'kind': 1, 'price_request': '80.39', 'price_open': 79.509, 'stop_loss': 'None', 'take_profit': 'None', 'comment': 'RoboSignal #1', 'magic': 123456, 'ticket': 363928013, 'open_at': '2020.10.22 06:36:53', 'response': 'ERROR_SETTING_SL_TP', 'response_value': 'None', 'environment': 'local'
        }
        expect(JSON.parse(response.body)['state']).to eq('error')
      end
    end

  end



  # describe API::V1::Orders do
  #   context 'POST /api/v1/orders' do
  #     it 'returns an empty array of statuses' do
  #       post '/api/v1/orders', params: order_attributes#, session: valid_session
  #       expect(response).to be_success
  #       expect(response.status).to eq(200)
  #       expect(JSON.parse(response.body)).to eq []
  #     end
  #   end
  #   # context 'GET /api/statuses/:id' do
  #   #   it 'returns a status by id' do
  #   #     status = Status.create!
  #   #     get "/api/statuses/#{status.id}"
  #   #     expect(response.body).to eq status.to_json
  #   #   end
  #   # end
  # end
end
