require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

# RSpec.describe Finances::EntriesController, type: :controller do
RSpec.describe API::V1::Orders do
  let(:trace_attributes) {
    
  }

  before(:context) do
    post '/api/v1/orders', params: {
      "message_id"=>"723517440",
      "message"=>"BUY 80.39\n\nTP 80.19\nTP 79.89\nTP 79.39\nSL 81.39",
      "photo_path"=>"/tmp/500028400464_282900.jpg",
      "name"=>"RoboSignal",
      "name_id"=>"-481414224"
    }
     #, session: valid_session
  end

  # This should return the minimal set of attributes required to create a valid
  # Finances::Entry. As you add validations to Finances::Entry, be sure to
  # adjust the attributes here as well.

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Finances::EntriesController. Be sure to keep this updated too.
  let(:job_image_worker) { ImageWorker.new.perform.first }

  describe API::V1::Traces do
    context 'POST /api/v1/orders' do
      it 'save a telegram trace message' do
        expect(job_image_worker.state).to be == "prepared"
        expect(job_image_worker.symbol).to be == "CADJPY"
        # expect(response).to be_success
        expect(response.status).to eq(201)
        # binding.pry
        expect(JSON.parse(response.body)).to be == {"id"=>1, "message"=>"BUY 80.39\n\nTP 80.19\nTP 79.89\nTP 79.39\nSL 81.39", "message_id"=>"723517440", "symbol"=>nil, "trace"=>"RoboSignal"}
      end
    end



    context 'GET /api/v1/orders/723517440' do
      it 'get information of message id' do
        job_image_worker
        get '/api/v1/orders/723517440'
        expect(JSON.parse(response.body)['id']).to eq(1)
        expect(JSON.parse(response.body)['message_id']).to eq('723517440')
        expect(JSON.parse(response.body)['message'].tr("\n", " ")).to be == 'BUY 80.39  TP 80.19 TP 79.89 TP 79.39 SL 81.39'
        expect(JSON.parse(response.body)['symbol']).to eq('CADJPY')
      end
    end

    context 'GET /api/v1/orders/' do
      it 'return all sign to execute' do
        job_image_worker
        get '/api/v1/stores'
        # expect(response).to be_success
        expect(response.status).to eq(200)
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['message_id']).to eq('723517440')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['type']).to eq('BUY')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['symbol']).to eq('CADJPY')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['price_request']).to eq('80.39')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['SL']).to eq('81.39')
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['TP']).to eq(['80.19', '79.89'])
        expect(JSON.parse(response.body)['traces'][0]['orders'][0]['lots']).to eq([0.03, 0.02])
      end
    end
    context 'POST /api/v1/orders/transaction' do
      it 'Save transaction from metatrader order' do
        job_image_worker
        post '/api/v1/orders/transaction', params:{
          "chat_id"=>"1",
          "message_id"=>"723517440",
          "provider"=>"1",
          "provider_name"=>"RoboSignal",
          "symbol"=>"CADJPY",
          "action"=>"EXECUTION",
          "kind"=>"0",
          "price_request"=>"80.39",
          "price_open"=>"80.38",
          "stop_loss"=>"81.39",
          "take_profit"=>"80.19",
          "comment"=>"RoboSignal",
          "magic"=>"123456",
          "ticket"=>"363873673",
          "open_at"=>"2020.10.21 01:18:09"
        }
        expect(JSON.parse(response.body)['state']).to eq('executed')
        expect(JSON.parse(response.body)['ticket']).to eq('363873673')
        expect(JSON.parse(response.body)['action']).to eq('EXECUTION')
        expect(JSON.parse(response.body)['kind']).to eq('0')
        expect(JSON.parse(response.body)['symbol']).to eq('CADJPY')
        expect(JSON.parse(response.body)['price_request']).to eq('80.39')
        expect(JSON.parse(response.body)['price_open']).to eq('80.38')
        expect(JSON.parse(response.body)['stop_loss']).to eq('81.39')
        expect(JSON.parse(response.body)['take_profit']).to eq('80.19')
        expect(JSON.parse(response.body)['comment']).to eq('RoboSignal')
        expect(JSON.parse(response.body)['magic']).to eq('123456')
        expect(JSON.parse(response.body)['ticket']).to eq('363873673')
        expect(JSON.parse(response.body)['open_at']).to eq('2020-10-21T01:18:09.000Z')

      end
    end
    context 'POST /api/v1/orders' do
      it 'Error transaction from metatrader order' do
        job_image_worker
        post '/api/v1/orders/transaction', params:{
          'chat_id': 1, 'message_id': '723517440', 'provider': 1, 'provider_name': 'RoboSignal', 'symbol': 'CADJPY', 'action': 'EXECUTION', 'kind': 1, 'price_request': '80.39', 'price_open': 79.509, 'stop_loss': 'None', 'take_profit': 'None', 'comment': 'RoboSignal #1', 'magic': 123456, 'ticket': 363928013, 'open_at': '2020.10.22 06:36:53', 'response': 'ERROR_SETTING_SL_TP', 'response_value': 'None', 'environment': 'local'
        }
        expect(JSON.parse(response.body)['state']).to eq('error')
      end
    end
  end



  # describe API::V1::Orders do
  #   context 'POST /api/v1/orders' do
  #     it 'returns an empty array of statuses' do
  #       post '/api/v1/orders', params: order_attributes#, session: valid_session
  #       expect(response).to be_success
  #       expect(response.status).to eq(200)
  #       expect(JSON.parse(response.body)).to eq []
  #     end
  #   end
  #   # context 'GET /api/statuses/:id' do
  #   #   it 'returns a status by id' do
  #   #     status = Status.create!
  #   #     get "/api/statuses/#{status.id}"
  #   #     expect(response.body).to eq status.to_json
  #   #   end
  #   # end
  # end
end
