## TODO 
# - SHOW LAST CONNECTION AND INFORMATION ABOUT SLAVE AND COPY EXPERT ON APP
# - VERIFY CLOSE TRANSACTIONS ON EXPERT STARTUP

## DONE
# - SHUTDOWN EXPERTS IF ACCOUNT IS DISABLE WITHOUT NEED RESTART ON EXPERT
# - MQL - MODE ACCOUNT MUST BE VERIFY 
# - ONLY EXPERT VERSION XXX SHOULD WORKS 
