## TODO 
## - SHUTDOWN EXPERTS IF ACCOUNT IS DISABLE WITHOUT NEED RESTART ON EXPERT
## - SHOW LAST CONNECTION AND INFORMATION ABOUT SLAVE AND COPY EXPERT ON APP

## - ONLY EXPERT VERSION XXX SHOULD WORKS 
## - VERIFY CLOSE TRANSACTIONS ON EXPERT STARTUP
