## TODO 
# - SHOW LAST CONNECTION AND INFORMATION ABOUT SLAVE AND COPY EXPERT ON APP
# - VERIFY CLOSE TRANSACTIONS ON EXPERT STARTUP
# - SHOULD VERIFY USER EMAIL TO CONNECT ON EXPERTS
# - VERSION OF EXPERT SHOULD BE VALIDATE ON ALL API CONNECTION

## DONE
# - SHUTDOWN EXPERTS IF ACCOUNT IS DISABLE WITHOUT NEED RESTART ON EXPERT
# - MQL - MODE ACCOUNT MUST BE VERIFY 
# - ONLY EXPERT VERSION XXX SHOULD WORKS 
