require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there ics no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe 'Store Controller', type: :request do
  before(:context) do
    unfreeze_time
    travel_to Date.parse('2023-06-01')
    @plan1 = create(:plan, :plan1)
    @store = create(:store, plan_id: @plan1.id)
    @plan_method = create(:payment_method, :mercadopago)
    @payment = create(:payment, :mercadopago, payment_method: @plan_method, store: @store)
    @customer_plan = create(:customer_plan, :premium, payment: @payment, store:@store)
    @trace = create(:trace, :copy, stores: [@store], instrument_control: true, customer_plans: [@customer_plan])
    @plan2 = create(:plan, :plan2)
    @store2 = create(:store, :store2, plan_id: @plan2.id)
    @trace2 = create(:trace, :copy2, stores: [@store2], instrument_control: true, customer_plans: [@customer_plan])
    @user_customer = create(:user, :customer, store: @store2)
    @customer = create(:customer, :customer, user:@user_customer, customer_plans:[@customer_plan])
    @account_copy = create(:account, :copy, store: @store2, customer:@customer, meta_margin_mode: 'hedging', trace_ids: [@trace2.id], instrument_control:true)

    @customer_plan = @trace.customer_plans.first

    @payment_mpago = @store.payments.first
    @payment_stripe = @store.payments.last

  end
  # This should return the minimal set of attributes required to create a valid
  # Order. As you add validations to Order, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { 'name': 'ONE', 'customer_plan_id': '1', 'account': { 'store_id': '1', 'name': '123456789', 'kind': 'slave',
                                                           'customer_attributes': { 'store_id': '1', 'name': 'Joao Cliente', 'user_attributes': { 'email': 'teste@cliente.com', 'store_id': '1' } },
                                                           'settings': { 'contract_volume': '1' }, 'meta_margin_mode': 'hedging', 'meta_mode': 'demo' }, "store_name": 'store1' }
  end  

  def valid_attributes_store2
    { 'name': 'ONE2', 'customer_plan_id': '3', 'account': { 'store_id': '2', 'name': '12345678', 'kind': 'slave',
                                                           'customer_attributes': { 'store_id': '2', 'name': 'Joao Cliente 2', 'user_attributes': { 'email': 'teste2@cliente.com', 'store_id': '2' } },
                                                           'settings': { 'contract_volume': '1' }, 'meta_margin_mode': 'hedging', 'meta_mode': 'demo' }, "store_name": 'store2' }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe 'Contract Trace on dashboards' do
    it 'Verify MercadoLivre Redirect' do
      expect(@store.payment_methods.first.handle).to be == 'mercado_pago'
      expect(@trace.customer_plans.first.payment.payment_method.handle).to be == 'mercado_pago'
      expect do
        post "/dashboard/#{@store.url}/#{@trace.name}/contract", params: valid_attributes # , valid_session
        @store.reload
      end.to change(Account, :count).by(1)
      expect(@store.sinvoices.all.count).to be == 1
      invoice = @store.sinvoices.first
      invoice.items.update_all(invoice_id: 41)
      invoice.update_columns(id: 41, state: Invoice.states[:to_paid], payment_id: @payment_mpago.id)
      
      # Initialize response hash to avoid nil errors
      invoice.update(response: {})
      
      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"api_version"=>"v1", "data"=>{"id"=>"1319796651"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"0", "data.id"=>"1319796651", "payment_id"=>"1", "mercadopago"=>{"action"=>"webhook", "api_version"=>"v1", "data"=>{"id"=>"1319796651"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"0"}}
        invoice.reload
      }.to change(invoice, :state).from("to_paid").to("paid")
      expect(response).to have_http_status 201
    end

    it 'Promition_page and promotion_use TRUE' do
      expect do
        post "/dashboard/#{@store.url}/#{@trace.name}/contract", params: valid_attributes # , valid_session
      end.to change(Account, :count).by(1)
      account = Account.find_by_name('123456789')
      expect(account.name).to be                  == '123456789'
      expect(account.meta_mode).to be             == 'demo'
      expect(account.meta_margin_mode).to be      == 'hedging'
      expect(account.state).to be                 == 'enable'
      expect(account.traces.count).to be          == 1
      expect(account.traces.name).to be           == 'Trace'
      expect(account.contract_volume).to be       == '1'
      expect(account.customer.name).to be         == 'Joao Cliente'
      expect(account.customer.role).to be         == 'customer'
      expect(account.customer.role_control).to be == 'user'
      expect(account.customer.customer_plans.first.name).to be == 'plan1'
    end
    it 'Promition_page and promotion_use TRUE' do
      @customer_plan = @trace.customer_plans.first
      @customer_plan.discount_behavior = 'promition_page'
      @customer_plan.amount_discount = '30%'
      @customer_plan.promotion_use = true
      @customer_plan.save
      @customer_plan.traces << @trace
      unfreeze_time
      travel_to Date.parse('2023-06-01').beginning_of_month
      freeze_time
      expect(@customer_plan.amount.to_f).to be == 100

      expect do
        post "/dashboard/#{@store.url}/#{@trace.name}/contract", params: valid_attributes # , valid_session
      end.to change(Account, :count).by(1)
      expect(response).to have_http_status 302
      expect(Invoice.all.count).to be == 1

      account = Account.find_by_name('123456789')
      invoice_name = "#{account.id}-#{Time.zone.now.strftime('%Y-%m')}"
      # account.create_invoice_customer(invoice_name)
      # expect(Invoice.all.count).to be == 1

      expect(Invoice.first.name).to be == invoice_name
      expect(Invoice.first.amount.to_f).to be == 70.0

      expect(account.name).to be == '123456789'
      permission = Permission.where(trace: @trace, customer_plan: @customer_plan).last
      expect(permission).not_to be_nil
      expect(permission.plan_usage).not_to be_nil
      expect(permission.plan_usage.usageable.amount).to be == 100.00
      expect(permission.plan_usage.charged_at).to be == (DateTime.current + 15.days + 1.months).beginning_of_month
    end

    it 'Promition_page and promotion_use False' do
      @customer_plan = @trace.customer_plans.first
      @customer_plan.discount_behavior = 'promition_page'
      @customer_plan.amount_discount = '10'
      @customer_plan.promotion_use = false
      @customer_plan.save
      @customer_plan.traces << @trace
      unfreeze_time
      travel_to Date.parse('2023-06-15').beginning_of_month
      freeze_time

      expect do
        post "/dashboard/#{@store.url}/#{@trace.name}/contract", params: valid_attributes # , valid_session
      end.to change(Account, :count).by(1)
      expect(response).to have_http_status 302
      expect(Invoice.all.count).to be == 1

      account = Account.find_by_name('123456789')
      invoice_name = "#{account.id}-#{Time.zone.now.strftime('%Y-%m')}"
      expect(Invoice.first.name).to be == invoice_name
      expect(Invoice.first.amount.to_f).to be == 100.0

      expect(account.name).to be == '123456789'
      permission = Permission.where(trace: @trace, customer_plan: @customer_plan).last
      expect(permission).not_to be_nil
      expect(permission.plan_usage).not_to be_nil
      expect(permission.plan_usage.usageable.amount).to be == 100.00
      expect(permission.plan_usage.charged_at).to be == (DateTime.current + 15.days + 1.months).beginning_of_month
    end

    it 'Always and promotion_use False' do
      @customer_plan = @trace.customer_plan
      @customer_plan.discount_behavior = 'always'
      @customer_plan.amount_discount = '50'
      @customer_plan.promotion_use = false
      @customer_plan.save
      @customer_plan.traces << @trace
      unfreeze_time
      travel_to Date.parse('2023-06-15').beginning_of_month
      freeze_time

      expect do
        post "/dashboard/#{@store.url}/#{@trace.name}/contract", params: valid_attributes # , valid_session
      end.to change(Account, :count).by(1)
      expect(response).to have_http_status 302
      expect(Invoice.all.count).to be == 1

      account = Account.find_by_name('123456789')
      invoice_name = "#{account.id}-#{Time.zone.now.strftime('%Y-%m')}"
      expect(Invoice.all.count).to be == 1
      expect(Invoice.first.name).to be == invoice_name
      expect(Invoice.first.amount.to_f).to be == 50.0

      expect(account.name).to be == '123456789'
      permission = Permission.where(trace: @trace, customer_plan: @customer_plan).last
      expect(permission).not_to be_nil
      expect(permission.plan_usage).not_to be_nil
      expect(permission.plan_usage.usageable.amount).to be == 100.00
      expect(permission.plan_usage.charged_at).to be == (DateTime.current + 15.days + 1.months).beginning_of_month
    end

    it 'None Promotion_use TRUE' do
      @customer_plan = @trace.customer_plans.first
      @customer_plan.discount_behavior = 'none'
      @customer_plan.amount_discount = '50'
      @customer_plan.promotion_use = true
      @customer_plan.save
      @customer_plan.traces << @trace
      unfreeze_time
      travel_to Date.parse('2023-06-15').beginning_of_month
      freeze_time

      expect do
        post "/dashboard/#{@store.url}/#{@trace.name}/contract", params: valid_attributes # , valid_session
      end.to change(Account, :count).by(1)
      expect(response).to have_http_status 302
      expect(Invoice.all.count).to be == 1

      account = Account.find_by_name('123456789')
      invoice_name = "#{account.id}-#{Time.zone.now.strftime('%Y-%m')}"
      expect(Invoice.all.count).to be == 1
      expect(Invoice.first.name).to be == invoice_name
      expect(Invoice.first.amount.to_f).to be == 100.0

      expect(account.name).to be == '123456789'
      permission = Permission.where(trace: @trace, customer_plan: @customer_plan).last
      expect(permission).not_to be_nil
      expect(permission.plan_usage).not_to be_nil
      expect(permission.plan_usage.usageable.amount).to be == 100.00
      expect(permission.plan_usage.charged_at).to be == (DateTime.current + 15.days + 1.months).beginning_of_month
    end
  end
  describe 'Contract Trace on dashboards' do
    it 'Store 1 with date Proportional' do
      @customer_plan = @trace.customer_plans.first
      @customer_plan.traces << @trace
      unfreeze_time
      travel_to Date.parse('2023-06-15').beginning_of_day
      freeze_time

      expect do
        post "/dashboard/#{@store.url}/#{@trace.name}/contract", params: valid_attributes # , valid_session
      end.to change(Account, :count).by(1)
      expect(response).to have_http_status 302
      expect(Invoice.all.count).to be == 1

      account = Account.find_by_name('123456789')
      invoice_name = "#{account.id}-#{Time.zone.now.strftime('%Y-%m')}"
      expect(Invoice.all.count).to be == 1
      expect(Invoice.first.name).to be == invoice_name
      expect(Invoice.first.amount.to_f).to be == 53.33

      expect(account.name).to be == '123456789'
      permission = Permission.where(trace: @trace, customer_plan: @customer_plan).last
      expect(permission).not_to be_nil
      expect(permission.plan_usage).not_to be_nil
      expect(permission.plan_usage.usageable.amount).to be == 100.00
      expect(permission.plan_usage.charged_at).to be == (DateTime.current + 15.days + 1.months).beginning_of_month
    end

    it 'Store 2 with date Proportional' do
      customer_plan = @store2.customer_plans.last
      customer_plan.discount_behavior = 'always'
      customer_plan.save
      # customer_plan.traces << @trace2
      @trace2.customer_plan = customer_plan
      unfreeze_time
      travel_to Date.parse('2023-06-15').beginning_of_day
      freeze_time

      expect do
        # post "/dashboard/#{@store.url}/#{@trace2.name}/contract" , params: {name: @trace2.name, customer_plan_id: customer_plan, :account :  valid_attributes} #, valid_session
        post "/dashboard/#{@store2.url}/#{@trace2.name}/contract", params: valid_attributes_store2.merge(name: @trace2.name) # , valid_session
      end.to change(Account, :count).by(1)
      expect(response).to have_http_status 302
      expect(Invoice.all.count).to be == 1

      account = Account.find_by_name('12345678')
      customer_plan = @trace2.customer_plan
      expect(account.store_id).to be == 2
      expect(customer_plan.amount).to be == 100
      expect(customer_plan.amount_discount).to be == 30
      expect(customer_plan.fixed?).to be true
      expect(customer_plan.percent?).not_to be true
      invoice_name = "#{account.id}-#{Time.zone.now.strftime('%Y-%m')}"
      expect(Invoice.all.count).to be == 1
      expect(Invoice.first.name).to be == invoice_name
      expect(Invoice.first.amount.to_f).to be == 37.33

      # expect(Invoice.first.plan_usage.plan_serializer["settings"]["amount_discount"]).to be == 30

      expect(account.name).to be == '12345678'
      permission = Permission.where(trace: @trace2, customer_plan: customer_plan).last
      expect(permission).not_to be_nil
    end

    it 'Semester' do
      @customer_plan = @trace.customer_plans.last
      # @customer_plan.trace_ids = [@trace.id]
      @customer_plan.charge_recurrence = :semester
      @customer_plan.kind = :fixed
      @customer_plan.save
      @trace.customer_plan = @customer_plan

      travel_to(DateTime.current.end_of_month - 15.days)
      freeze_time

      expect do
        post "/dashboard/#{@store.url}/#{@trace.name}/contract", params: valid_attributes # , valid_session
      end.to change(Account, :count).by(1)
      expect(response).to have_http_status 302
      account = Account.find_by_name('123456789')
      invoice = account.customer.invoices.last
      
      expect(invoice.id).to be == 9
      expect(invoice.amount.to_f).to be == 50.0

      expect(account.contract_volume).to be ==  "1"
      invoice_name = "#{account.id}-#{Time.zone.now.strftime('%Y-%m')}"
      expect(Invoice.all.count).to be == 1
      expect(invoice.name).to be == invoice_name

      expect(account.name).to be == '123456789'
      permission = Permission.where(trace: @trace, customer_plan: @customer_plan).last
      expect(permission).not_to be_nil
      expect(permission.plan_usage).not_to be_nil
      expect(permission.plan_usage.usageable.amount).to be == 100.00
      expect(permission.plan_usage.charged_at).to be == (DateTime.current + 15.days + 6.months).beginning_of_month
    end

    it 'Store 2 - CustomerPlan Percent' do

      unfreeze_time
      travel_to Date.parse('2023-06-15').beginning_of_day
      freeze_time

      customer_plan = @store2.customer_plans.last
      customer_plan.discount_behavior = 'always'
      customer_plan.save
      # customer_plan.traces << @trace2
      @trace2 = Trace.last
      @trace2.customer_plan = customer_plan

      order_date = (DateTime.current - 20.seconds).strftime("%Y.%m.%d %H:%M:%S")

      expect do
        # post "/dashboard/#{@store.url}/#{@trace2.name}/contract" , params: {name: @trace2.name, customer_plan_id: customer_plan, :account :  valid_attributes} #, valid_session
        post "/dashboard/#{@store2.url}/#{@trace2.name}/contract", params: valid_attributes_store2.merge(name: @trace2.name) # , valid_session
      end.to change(Account, :count).by(1)
      expect(response).to have_http_status 302
      expect(Invoice.all.count).to be == 1
      expect(Transaction.all.count).to be == 0
      expect(TransactionSlave.count).to be == 0
      post '/api/v2/copy/post/imentore_copy/2_21/broker_name/10100/HEDGING',
          params: {"imentore_copy"=>
              "{\"orders_open\":{
                  \"10000020\":{\"symbol\":\"AUDCAD\",\"ticket_id\":10000020,\"ticket_deal\":2014200579,\"type\":0,\"price_open\":\"0.87401\",\"price_closed\":\"0.87314\",\"volume\":\"0.02\",\"profit\":\"-1.30\",\"fees\":\"-0.0600\",\"stop_loss\":0.00000000,\"take_profit\":0.00000000,\"mae\":\"0.00\",\"mfe\":\"0.00\",\"open_at\":\'#{order_date}\',\"close_at\":\'#{nil}\',\"time_gmt\":\'#{order_date}\',\"time_trader\":\'#{order_date}\',\"timezone\":-3,\"symbol_digit\":5,\"magic_number\":20001,\"comment\":null}
                }}"}  
  
      expect(Transaction.all.count).to be == 1
      expect(TransactionSlave.count).to be == 1

      account = Account.find_by_name('12345678')
      slave = account.slaves.first
      slave.update(profit: 10.0, state: 'executed')
      slave.close
      account = Account.find_by_name('12345678')

      customer_plan = @trace2.customer_plan
      expect(account.store_id).to be == 2
      expect(customer_plan.amount_discount).to be == 30
      expect(customer_plan.amount).to be == 100
      expect(customer_plan.fixed?).to be true
      expect(customer_plan.percent?).to be false
      invoice_name = "#{account.id}-#{Time.zone.now.strftime('%Y-%m')}"
      account.add_account_trace_to_planusage(@trace2, customer_plan)
      account.create_invoice(@trace2, true, nil)
      expect(Invoice.all.count).to be == 1
      expect(Invoice.first.name).to be == invoice_name
      expect(Invoice.first.amount.to_f).to be == 37.33

      # expect(Invoice.first.plan_usage.plan_serializer["settings"]["amount_discount"]).to be == 30

      expect(account.name).to be == '12345678'
      permission = Permission.where(trace: @trace2, customer_plan: customer_plan).last
      expect(permission).not_to be_nil
    end

  end
end