require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe 'Store Controller', type: :request do
	before(:context) do
    unfreeze_time
    travel_to Date.parse("2023-06-01")
	  @plan1 = create(:plan, :plan1)
    @store = create(:store, plan_id: @plan1.id)
    @trace = create(:trace, :copy, store: @store, instrument_control: true)
    @customer_plan = @store.customer_plans.first


	end
  # This should return the minimal set of attributes required to create a valid
  # Order. As you add validations to Order, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    # { "name"=>"Store1", "email"=>"store1@email.com", "password"=>"123123", "url"=>"store1", "plan_id"=>"1" }
    {"store_id"=>"1", "name"=>"12345678", "kind"=>"slave", "customer_attributes"=>{"store_id"=>"1", "name"=>"Test Dash", "user_attributes"=>{"email"=>"testdash@email.com", "store_id"=>"1"}}, "meta_margin_mode"=>"hedging", "meta_mode"=>"demo"}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "POST create /stores/create" do #, focus:true do
    describe "with valid params" do
      it "creates a new Order" do
       @customer_plan = @store.customer_plans.first
       @customer_plan.traces << @trace
       unfreeze_time
       travel_to Date.parse("2023-06-15").beginning_of_day
       freeze_time

        expect {
          post "/dashboards/#{@trace.id}/contract" , params: {id: @trace.id, customer_plan_id: @customer_plan.id, :account => valid_attributes} #, valid_session
        }.to change(Account, :count).by(1)
       expect(response).to have_http_status 302
       expect(Invoice.all.count).to be == 0


       account = Account.find_by_name("12345678")
       invoice_name = "Trace##{@trace.id}-Account##{account.id}-#{Time.zone.now.strftime("%Y-%m")}" 
       account.customer.create_invoice_customer(invoice_name)
       expect(Invoice.all.count).to be == 1
       expect(Invoice.first.name).to be == invoice_name
       expect(Invoice.first.amount.to_f).to be == 53.33


       expect(account.name).to be == "12345678"
       permission = Permission.where(trace: @trace, customer_plan:@customer_plan).last
       expect(permission).not_to be_nil
       expect(permission.plan_usage).not_to be_nil
       expect(permission.plan_usage.usageable.amount).to be == 100.00
       expect(permission.plan_usage.charged_at).to be == (DateTime.now + 15.days + 1.months).beginning_of_month
      end

      it "creates a new Order" do

       @customer_plan = @store.customer_plans.first
       @customer_plan.trace_ids = [@trace.id]
       @customer_plan.charge_recurrence = :semester
       @customer_plan.save

       travel_to (DateTime.now.end_of_month - 15.days)
       freeze_time

        expect {
          post "/dashboards/#{@trace.id}/contract" , params: {id: @trace.id, customer_plan_id: @customer_plan.id, :account => valid_attributes} #, valid_session
        }.to change(Account, :count).by(1)
       expect(response).to have_http_status 302
       expect(Invoice.all.count).to be == 0


       account = Account.find_by_name("12345678")
       invoice_name = "Trace##{@trace.id}-Account##{account.id}-#{Time.zone.now.strftime("%Y-%m")}" 
       account.customer.create_invoice_customer(invoice_name)
       expect(Invoice.all.count).to be == 1
       expect(Invoice.first.name).to be == invoice_name
       expect(Invoice.first.amount.to_f).to be == 100.0


       expect(account.name).to be == "12345678"
       permission = Permission.where(trace: @trace, customer_plan:@customer_plan).last
       expect(permission).not_to be_nil
       expect(permission.plan_usage).not_to be_nil
       expect(permission.plan_usage.usageable.amount).to be == 100.00
       expect(permission.plan_usage.charged_at).to be == (DateTime.now + 15.days + 6.months).beginning_of_month
      end
      # it "creates a new Order" do
      #   expect {
      #     post '/stores' , params: {:store => valid_attributes} #, valid_session
      #   }.to change { ActionMailer::Base.deliveries.count }.by(1)
      # end
    end
  end
end