require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there ics no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe 'Store Controller', type: :request do
  before(:context) do
    @plan1 = create(:plan, :plan1)
    @store = create(:store, plan_id: @plan1.id)
    @trace = create(:trace, :copy, stores: [@store], instrument_control: true)
    @customer_plan  = @store.customer_plans.first
    @user_customer  = create(:user, :customer, store: @store)
    @user_admin     = create(:user, :admin, store: @store)
    @admin          = create(:customer, :admin, user:@user_admin)
    @customer       = create(:customer, :customer, user:@user_customer)
    @account_copy   = create(:account, :copy, store: @store, customer:@customer, meta_margin_mode: 'hedging', traces: [@trace])
    @account_slave  = create(:account, :slave1, store: @store, customer:@customer, meta_margin_mode: 'hedging', traces: [@trace])

  end
  # This should return the minimal set of attributes required to create a valid
  # Order. As you add validations to Order, be sure to
  # update the return value of this method accordingly.

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe 'Dashboards Controllers' do
    it '#index ' do
      get "/dashboards/#{@store.url}"
      expect(response).to have_http_status 200
    end

    it '#show ' do
      get "/dashboard/#{@store.url}/#{@trace.name}"
      expect(response).to have_http_status 200
    end
    
    it '#contract ' do
      get "/dashboard/#{@store.url}/#{@trace.name}/contract"
      expect(response).to have_http_status 200
    end

    it '#account #copy ' do
      get "/dashboard/#{@store.url}/#{@trace.name}/account/#{@account_copy.id}"
      expect(response).to have_http_status 200
    end

    it '#account #slave ' do
      get "/dashboard/#{@store.url}/#{@trace.name}/account/#{@account_slave.id}"
      expect(response).to have_http_status 200
    end

    it '#account #copy 'do
      account = Account.find_by(name: 10100)
      expect(account.kind).to be == "copy"
      expect(account.state).to be == "enable"
      account.update(state: 'enable')
      account.reload
      post '/api/v2/copy/post/imentore_copy/2_21/broker_name/10100/HEDGING',
          params: {"imentore_copy"=>
              "{\"orders_open\":{
                  \"10000019\":{\"symbol\":\"AUDCAD\",\"ticket_id\":10000019,\"ticket_deal\":2014200579,\"type\":0,\"price_open\":\"0.87401\",\"price_closed\":\"0.87314\",\"volume\":\"0.02\",\"profit\":\"-1.30\",\"fees\":\"-0.0600\",\"stop_loss\":0.00000000,\"take_profit\":0.00000000,\"mae\":\"0.00\",\"mfe\":\"0.00\",\"open_at\":\"2023.08.02 16:01:23\",\"close_at\":\"2023.08.02 21:44:28\",\"time_gmt\":\"2023.08.02 19:45:38\",\"time_trader\":\"2023.08.02 22:45:38\",\"timezone\":-6,\"symbol_digit\":5,\"magic_number\":20000,\"comment\":null}
                }}"}  
      transaction = account.transactions.first
      expect(transaction.id).to be == 1
      expect(account.transactions.count).to be == 1
      
      get "/dashboard/#{@store.url}/#{@trace.name}/account/#{@account_copy.id}/#{transaction.id}"
      expect(response).to have_http_status 200
    end


  end
end
