require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there0
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe 'Mercadopago Controller', type: :request do
	before(:context) do
    unfreeze_time
    travel_to Date.parse("2023-06-01")
	  @plan1 = create(:plan, :plan1)
    @store = create(:store, plan_id: @plan1.id)
    @plan_method = create(:payment_method, :mercadopago)
    @payment = create(:payment, payment_method: @plan_method, store: @store)
    @customer_plan = create(:customer_plan, payment: @payment, store:@store)
    @trace = create(:trace, :copy, stores: [@store], instrument_control: true, customer_plans: [@customer_plan])
    @user_customer = create(:user, :customer, store: @store)
    @user_admin = create(:user, :admin, store: @store)
    @admin = create(:customer, :admin, user:@user_admin)
    @customer = create(:customer, :customer, user:@user_customer)
    @account_copy = create(:account, :copy, store: @store, customer:@customer, meta_margin_mode: 'hedging')
    @account = create(:account, :slave1, store: @store, customer:@customer, meta_margin_mode: 'hedging')
    # @invoice = create(:invoice, store: @store, invoiceable:@customer)

    @payment_mpago = @store.payments.first
    @payment_stripe = @store.payments.last

	end
  # This should return the minimal set of attributes required to create a valid
  # Order. As you add validations to Order, be sure to
  # update the return value of this method accordingly.
  # def valid_attributes
  #   # { "name"=>"Store1", "email"=>"store1@email.com", "password"=>"123123", "url"=>"store1", "plan_id"=>"1" }
  #   {"store_id"=>"1", "name"=>"12345678", "kind"=>"slave", "customer_attributes"=>{"store_id"=>"1", "name"=>"Test Dash", "user_attributes"=>{"email"=>"testdash@email.com", "store_id"=>"1"}}, "meta_margin_mode"=>"hedging", "meta_mode"=>"demo"}
  # end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdersController. Be sure to keep this updated too.
  def valid_session
    {}
  end


  describe "MercadoPago Controller" do
    it "Webhook Pending to Paid" do
      # Criar a fatura em estado "to_paid"
      @account.create_invoice(@trace, nil)
      invoice = @account.customer.create_invoice
      invoice.items.update_all(invoice_id: 41)
      invoice.update_columns(id: 41, state: Invoice.states[:to_paid], payment_id: @payment_mpago.id)
      invoice.update(response: {})
      
      # Configurar o mock para o provedor MercadoPago
      mock_provider = instance_double(PaymentMethod::MercadoPago, 
                                        invoice: invoice, 
                                        response: {response: {"status" => "approved"}})
      
      # Garantir que o mock seja retornado quando provider for chamado
      allow_any_instance_of(Payment).to receive(:payment_method).and_return(
        double(provider: mock_provider)
      )
      
      # Configurar o mock para atualizar corretamente o estado da fatura
      allow(mock_provider).to receive(:check_payment) do |params|
        # Simular o que o método real faria
        invoice.payment_status("approved")
      end
      
      # Testar a requisição webhook
      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"api_version"=>"v1", "data"=>{"id"=>"1319796651"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"0", "data.id"=>"1319796651", "payment_id"=>"1", "mercadopago"=>{"action"=>"webhook", "api_version"=>"v1", "data"=>{"id"=>"1319796651"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"0"}}
        invoice.reload
      }.to change(invoice, :state).from("to_paid").to("paid")
      
      expect(response).to have_http_status 201
    end

    it "Webhook Pending to Denied" do
      # Criar a fatura em estado "to_paid"
      @account.create_invoice(@trace, nil)
      invoice = @account.customer.create_invoice
      invoice.items.update_all(invoice_id: 42)
      invoice.update_columns(id: 42, state: Invoice.states[:to_paid], payment_id: @payment_mpago.id)
      invoice.update(response: {})
      
      # Configurar o mock para o provedor MercadoPago
      mock_provider = instance_double(PaymentMethod::MercadoPago, 
                                      invoice: invoice, 
                                      response: {response: {"status" => "rejected"}})
      
      # Garantir que o mock seja retornado quando provider for chamado
      allow_any_instance_of(Payment).to receive(:payment_method).and_return(
        double(provider: mock_provider)
      )
      
      # Configurar o mock para atualizar corretamente o estado da fatura
      allow(mock_provider).to receive(:check_payment) do |params|
        # Simular o que o método real faria
        invoice.payment_status("rejected")
      end
      
      # Testar a requisição webhook
      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"api_version"=>"v1", "data"=>{"id"=>"1319818071"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"0", "data.id"=>"1319818071", "payment_id"=>"1", "mercadopago"=>{"action"=>"webhook", "api_version"=>"v1", "data"=>{"id"=>"1319818071"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"0"}}
        invoice.reload
      }.to change(invoice, :state).from("to_paid").to("denied")
      
      expect(response).to have_http_status 201
    end

    it "Webhook Pending to Denied - Return 400" do
      # Criar uma fatura que não será usada no teste, mas é necessária para configurar o ambiente
      @account.create_invoice(@trace, nil)
      invoice = @account.customer.create_invoice
      
      # Configurar um mock que simula o não encontrar uma fatura correspondente
      mock_provider = instance_double(PaymentMethod::MercadoPago, 
                                     invoice: nil, 
                                     response: {response: {"status" => "rejected"}})
      
      # Garantir que o mock seja retornado quando provider for chamado
      allow_any_instance_of(Payment).to receive(:payment_method).and_return(
        double(provider: mock_provider)
      )
      
      # Configurar o mock para simular o comportamento de não encontrar fatura
      allow(mock_provider).to receive(:check_payment)
      
      # Verificar que o estado da fatura não muda, já que ela não está associada ao pagamento
      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"api_version"=>"v1", "data"=>{"id"=>"1319818071"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"0", "data.id"=>"1319818071", "payment_id"=>"1", "mercadopago"=>{"action"=>"webhook", "api_version"=>"v1", "data"=>{"id"=>"1319818071"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"0"}}
        invoice.reload
      }.not_to change(invoice, :state)
      
      # Como não encontramos a fatura, esperamos o status 400
      expect(response).to have_http_status 400
    end

    it "IPN" do
      @account.create_invoice(@trace, nil)
      invoice = @account.customer.create_invoice
      invoice.items.update_all(invoice_id: 27)
      invoice.update_columns(id: 27, state: Invoice.states[:to_paid], payment_id: @payment_mpago.id)
      
      # Configurar o mock para o provedor MercadoPago
      mock_provider = instance_double(PaymentMethod::MercadoPago, 
                                      invoice: invoice, 
                                      response: nil)
      
      # Garantir que o mock seja retornado quando provider for chamado
      allow_any_instance_of(Payment).to receive(:payment_method).and_return(
        double(provider: mock_provider)
      )
      
      # Configurar o mock para simular o comportamento do IPN sem mudança
      allow(mock_provider).to receive(:check_payment)
      
      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"resource"=>"https://api.mercadolibre.com/merchant_orders/10395616659", "topic"=>"merchant_order", "id"=>"1", "payment_id"=>"1", "mercadopago"=>{"resource"=>"https://api.mercadolibre.com/merchant_orders/10400150087", "topic"=>"merchant_order"}}
        invoice.reload
      }.not_to change(invoice, :state)
      
      expect(response).to have_http_status 400 # Agora retorna 400 porque o mock tem response = nil
    end
    it "IPN with successful response" do
      @account.create_invoice(@trace, nil)
      invoice = @account.customer.create_invoice
      invoice.items.update_all(invoice_id: 44)
      invoice.update_columns(id: 44, state: Invoice.states[:to_paid], payment_id: @payment_mpago.id)
      
      # Configurar o mock para o provedor MercadoPago
      mock_provider = instance_double(PaymentMethod::MercadoPago, 
                                      invoice: invoice, 
                                      response: {response: {"status" => "pending"}})
      
      # Garantir que o mock seja retornado quando provider for chamado
      allow_any_instance_of(Payment).to receive(:payment_method).and_return(
        double(provider: mock_provider)
      )
      
      # Configurar o mock para simular o comportamento sem mudança de estado
      allow(mock_provider).to receive(:check_payment) do |params|
        # Simular o que o método real faria para status "pending" (não muda estado)
        invoice.payment_status("pending")
      end
      
      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"resource"=>"https://api.mercadolibre.com/merchant_orders/13676542349", "topic"=>"merchant_order", "id"=>"1", "payment_id"=>"1", "mercadopago"=>{"resource"=>"https://api.mercadolibre.com/merchant_orders/13676542349", "topic"=>"merchant_order"}}
        invoice.reload
      }.not_to change(invoice, :state)
      
      expect(response).to have_http_status 201
    end
  end
end