require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe 'Mercadopago Controller', type: :request do
	before(:context) do
    unfreeze_time
    travel_to Date.parse("2023-06-01")
	  @plan1 = create(:plan, :plan1)
    @store = create(:store, plan_id: @plan1.id)
    @trace = create(:trace, :copy, store: @store, instrument_control: true)
    @user_customer = create(:user, :customer, store: @store)
    @user_admin = create(:user, :admin, store: @store)
    @admin = create(:customer, :admin, store:@store, user:@user_admin)
    @customer = create(:customer, :customer, store:@store, user:@user_customer)
    @account_copy = create(:account, :copy, store: @store, customer:@customer, meta_margin_mode: 'hedging')
    @account = create(:account, :slave1, store: @store, customer:@customer, meta_margin_mode: 'hedging')
    # @invoice = create(:invoice, store: @store, invoiceable:@customer)

    @payment_mpago = @store.payments.first
    @payment_stripe = @store.payments.last

	end
  # This should return the minimal set of attributes required to create a valid
  # Order. As you add validations to Order, be sure to
  # update the return value of this method accordingly.
  # def valid_attributes
  #   # { "name"=>"Store1", "email"=>"store1@email.com", "password"=>"123123", "url"=>"store1", "plan_id"=>"1" }
  #   {"store_id"=>"1", "name"=>"12345678", "kind"=>"slave", "customer_attributes"=>{"store_id"=>"1", "name"=>"Test Dash", "user_attributes"=>{"email"=>"testdash@email.com", "store_id"=>"1"}}, "meta_margin_mode"=>"hedging", "meta_mode"=>"demo"}
  # end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdersController. Be sure to keep this updated too.
  def valid_session
    {}
  end


  describe "MercadoPago Controller" do
    it "Webhook Pending to Paid" do
      # unfreeze_time
      # travel_to Date.parse("2023-06-01").beginning_of_month
      # freeze_time

      @account.add_account_trace_to_planusage(@trace, @customer.customer_plans.first)

      invoice_name = "Trace##{@trace.id}-Account##{@account.id}-#{Time.zone.now.strftime("%Y-%m")}" 
      invoice = @account.customer.create_invoice_customer(invoice_name)
      invoice.items.update_all(invoice_id:28)
      invoice.update_columns(id:28)

      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"api_version"=>"v1", "data"=>{"id"=>"1313825330"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"77964627", "data.id"=>"1313825330", "payment_id"=>"1", "mercadopago"=>{"action"=>"webhook", "api_version"=>"v1", "data"=>{"id"=>"1313825330"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"77964627"}}
        invoice.reload
      }.to change(invoice, :state).from("pending").to("paid")
      expect(response).to have_http_status 201
    end

    it "Webhook 401" do
      # unfreeze_time
      # travel_to Date.parse("2023-06-01").beginning_of_month
      # freeze_time

      @account.add_account_trace_to_planusage(@trace, @customer.customer_plans.first)

      invoice_name = "Trace##{@trace.id}-Account##{@account.id}-#{Time.zone.now.strftime("%Y-%m")}" 
      invoice = @account.customer.create_invoice_customer(invoice_name)
      invoice.items.update_all(invoice_id:28)
      invoice.update_columns(id:28)

      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"api_version"=>"v1", "data"=>{"id"=>"131382533"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"77964627", "data.id"=>"1313825333", "payment_id"=>"1", "mercadopago"=>{"action"=>"webhook", "api_version"=>"v1", "data"=>{"id"=>"1313825333"}, "date_created"=>"2023-07-12T21:44:01Z", "id"=>"1", "live_mode"=>false, "type"=>"payment", "user_id"=>"77964627"}}
        invoice.reload
      }.not_to change(invoice, :state).from("pending")
      expect(response).to have_http_status 201
    end

    it "IPN" do
      # unfreeze_time
      # travel_to Date.parse("2023-06-01").beginning_of_month
      # freeze_time

      @account.add_account_trace_to_planusage(@trace, @customer.customer_plans.first)

      invoice_name = "Trace##{@trace.id}-Account##{@account.id}-#{Time.zone.now.strftime("%Y-%m")}" 
      invoice = @account.customer.create_invoice_customer(invoice_name)
      invoice.items.update_all(invoice_id:28)
      invoice.update_columns(id:28)

      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"resource"=>"https://api.mercadolibre.com/merchant_orders/10395616659", "topic"=>"merchant_order", "id"=>"1", "payment_id"=>"1", "mercadopago"=>{"resource"=>"https://api.mercadolibre.com/merchant_orders/10400150087", "topic"=>"merchant_order"}}
        invoice.reload
      }.not_to change(invoice, :state).from("pending")
      expect(response).to have_http_status 201
    end
    it "IPN" do
      # unfreeze_time
      # travel_to Date.parse("2023-06-01").beginning_of_month
      # freeze_time

      @account.add_account_trace_to_planusage(@trace, @customer.customer_plans.first)

      invoice_name = "Trace##{@trace.id}-Account##{@account.id}-#{Time.zone.now.strftime("%Y-%m")}" 
      invoice = @account.customer.create_invoice_customer(invoice_name)
      invoice.items.update_all(invoice_id:28)
      invoice.update_columns(id:28)

      expect {
        post "/mercadopago/webhook/#{@store.id}/#{@payment_mpago.id}", 
          params: {"resource"=>"https://api.mercadolibre.com/merchant_orders/10400150087", "topic"=>"merchant_order", "id"=>"1", "payment_id"=>"1", "mercadopago"=>{"resource"=>"https://api.mercadolibre.com/merchant_orders/10400150087", "topic"=>"merchant_order"}}
        invoice.reload
      }.to change(invoice, :state).from("pending")
      expect(response).to have_http_status 201
    end
  end
end