require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

# RSpec.describe Finances::EntriesController, type: :controller do
RSpec.describe Order do


  before(:context) do
    @store = create(:store, master: '5077669')
    @trace = create(:trace, :first, store: @store)
  end

  # This should return the minimal set of attributes required to create a valid
  # Finances::Entry. As you add validations to Finances::Entry, be sure to
  # adjust the attributes here as well.

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Finances::EntriesController. Be sure to keep this updated too.
  # let!(:store) { FactoryBot.create(:store)   }
  # let!(:trace) { FactoryBot.create(:trace, :first, store: store)}
  # let(:job_image_worker) { ImageWorker.new.perform.first }
  # let(:order) { FactoryBot.create(:order, :m15_trace) }
  # let(:transaction) { FactoryBot.create(:transaction) }

  describe 'Order and transaction' do
    context 'transaction order' do
      it 'transaction should not closed order' do
        @order = create(:order, :m15_trace_first, trace:@trace)
        @order.prepare
        @t1 = create(:transaction, :first, order:@order)
        @t2 = create(:transaction, :second, order:@order)
        @t1.execute
        @t2.execute
        @t2.close
        expect(@order.state).to be == ('executed')
        expect(@order.state).not_to be == ('closed')
      end
      it 'transaction should closed order' do
        @order = create(:order, :m15_trace_first, trace:@trace)
        @order.prepare
        @t1 = create(:transaction, :first, order:@order)
        @t2 = create(:transaction, :second, order:@order)
        @t1.execute
        @t2.execute
        @t1.close
        @t2.close
        expect(@order.state).not_to be == ('executed')
        expect(@order.state).to be == ('closed')
      end
    end
  end
end
