require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe 'Store Controller', type: :request do
	before(:context) do
	  @plan1  = create(:plan, :plan1)
    @store  = create(:store, plan: @plan1)
    @stripe = create(:payment_method, :stripe)
    @payment = create(:payment, payment_method: @stripe, store: @store)
    @store_name = "Sistema-#{Store.last.try(:id).to_i + 1}" 

    # @stripe = create(:payment_method, :mercadopago)
	end

  # This should return the minimal set of attributes required to create a valid
  # Order. As you add validations to Order, be sure to
  # update the return value of this method accordingly.
  
  
  def valid_attributes
    { "name"=>"#{@store_name}", "email"=>"store1@email.com", "password"=>"123123", "url"=>"store1", "plan_id"=>"1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdersController. Be sure to keep this updated too.
  def valid_session
    {}
  end


  describe "POST create /stores/create" do#, focus:true do
    describe "with valid params" do
      it "creates a new Order" do
        expect {
          post '/stores' , params: {:store => valid_attributes} #, valid_session
          @store.reload
        }.to change(Store, :count).by(1)
        @store = Store.last
        count = Store.count
        expect(response).to have_http_status 302
        expect(Store.all.count).to eq(count)
        expect(@store.name).to be == @store_name
        expect(@store.payment_id).to eq(1)
        expect(@store.payment_id).to eq(1)
        expect(@store.accounts.count).to eq(1)
        expect(@store.traces.count).to eq(1)

      end
      it "creates a new Order" do
        expect {
          post '/stores' , params: {:store => valid_attributes} #, valid_session
        }.to change { ActionMailer::Base.deliveries.count }.by(1)
      end
    end
  end
end