# class String
#   def to_underscore!
#     str = self
#     str.gsub!(/::/, '/')
#     str.gsub!(' ', '_')
#     str.gsub!(/([A-Z]+)([A-Z][a-z])/,'\1_\2')
#     str.gsub!(/([a-z\d])([A-Z])/,'\1_\2')
#     str.tr!("-", "_")
#     str.tr!("/", "_")
#     str.tr!("'", "_")
#     str.tr!("`", "_")
#     str.tr!(".", "_")
#     str.tr!(",", "_")
#     str.tr!("[", "_")
#     str.tr!("]", "_")
#     str.tr!("(", "_")
#     str.tr!(")", "_")
#     str.tr!("'", "_")
#     str.tr!('"', "_")
#     str.tr!("\\", "_")
#     str.tr!("!", "_")
#     str.tr!("&", "_")
#     str.tr!("!", "_")
#     str.tr!("?", "_")
#     str.tr!("#", "_")
#     str.tr!("-", "_")
#     str.tr!("+", "_")
#     str.tr!(":", "_")
#     str = str.gsub("___", "_")
#     str = str.gsub("__", "_")
#     str = str.gsub("*", "_")
#     str = I18n.transliterate(str)
#     str.downcase
#   end
#   def to_underscore
#     str = self
#     str = str.gsub(/::/, '/')
#     str = str.gsub(' ', '_')
#     str = str.gsub(/([A-Z]+)([A-Z][a-z])/,'\1_\2')
#     str = str.gsub(/([a-z\d])([A-Z])/,'\1_\2')
#     str = str.tr("-", "_")
#     str = str.tr("/", "_")
#     str = str.tr("'", "_")
#     str = str.tr("`", "_")
#     str = str.tr(".", "_")
#     str = str.tr(",", "_")
#     str = str.tr("[", "_")
#     str = str.tr("]", "_")
#     str = str.tr("(", "_")
#     str = str.tr(")", "_")
#     str = str.tr("'", "_")
#     str = str.tr('"', "_")
#     str = str.tr("\\", "_")
#     str = str.tr("!", "_")
#     str = str.tr("&", "_")
#     str = str.tr("!", "_")
#     str = str.tr("?", "_")
#     str = str.tr("#", "_")
#     str = str.tr("-", "_")
#     str = str.tr("+", "_")
#     str = str.tr(":", "_")
#     str = str.gsub("___", "_")
#     str = str.gsub("__", "_")
#     str = str.gsub("*", "_")
#     str = I18n.transliterate(str)
#     str.downcase
#   end
# end