TelegramWorker:
  # cron: '30 * * * * *'   # Runs once per minute
  every: ["6s"]
  class: TelegramWorker
  queue: default
  # args: contributors
  # description: 'This job resets the weekly leaderboard for contributions'
  # include_metadata: true
MetaWorker:
  # cron: '30 * * * * *'   # Runs once per minute
  every: ["3s"]
  class: MetaWorker
  queue: default
  # args: contributors
  # description: 'This job resets the weekly leaderboard for contributions'
  # include_metadata: true
