"""initial schema

Generated by `alembic revision --autogenerate`, then edited: enum columns are rendered as
VARCHAR(24) + the named CHECK constraints (autogenerate emitted each CHECK twice, which
Postgres rejects). Partial unique indexes carry sqlite_where and postgresql_where.

Revision ID: 0001
Revises:
Create Date: 2026-10-05 17:18:23.399145
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_server', sa.String(length=128), nullable=False),
    sa.Column('broker_server_norm', sa.String(length=128), nullable=False),
    sa.Column('login', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('margin_mode', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('suspended_reason', sa.String(length=255), nullable=True),
    sa.Column('ea_version', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('session_epoch', sa.Integer(), nullable=True),
    sa.Column('session_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seq', sa.BigInteger(), nullable=True),
    sa.Column('exclude_copier_positions', sa.Boolean(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('pending_token_hash', sa.String(length=64), nullable=True),
    sa.Column('pending_token_id', sa.String(length=64), nullable=True),
    sa.Column('pending_token_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("margin_mode IN ('hedging', 'netting', 'unknown')", name=op.f('ck_accounts_margin_mode')),
    sa.CheckConstraint("role IN ('master', 'slave')", name=op.f('ck_accounts_account_role')),
    sa.CheckConstraint("status IN ('active', 'suspended', 'revoked')", name=op.f('ck_accounts_account_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('broker_server_norm', 'login', 'role', name=op.f('uq_accounts_broker_server_norm_login_role'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_pending_token_hash'), ['pending_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_token_hash'), ['token_hash'], unique=False)

    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_tokens_token_hash'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_undelivered', ['delivered_at', 'id'], unique=False)

    op.create_table('copy_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('magic_allow', sa.JSON(), nullable=True),
    sa.Column('symbol_filter', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['accounts.id'], name=op.f('fk_copy_groups_master_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copy_groups'))
    )
    with op.batch_alter_table('copy_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copy_groups_master_id'), ['master_id'], unique=False)

    op.create_table('ea_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_ea_logs_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ea_logs'))
    )
    with op.batch_alter_table('ea_logs', schema=None) as batch_op:
        batch_op.create_index('ix_ea_logs_account_received', ['account_id', 'received_at'], unique=False)

    op.create_table('enroll_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('server_norm', sa.String(length=128), nullable=True),
    sa.Column('login', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=True),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_token_hash', sa.String(length=64), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('master', 'slave')", name=op.f('ck_enroll_codes_enroll_role')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_enroll_codes_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enroll_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_enroll_codes_code_hash'))
    )
    with op.batch_alter_table('enroll_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enroll_codes_account_id'), ['account_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('route', sa.String(length=128), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind <> 'token' OR response IS NULL", name=op.f('ck_idempotency_keys_token_response_never_stored')),
    sa.CheckConstraint("kind IN ('response', 'token')", name=op.f('ck_idempotency_keys_idempotency_kind')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_idempotency_keys_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'key', name=op.f('pk_idempotency_keys'))
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_created_at'), ['created_at'], unique=False)

    op.create_table('inbound_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.CheckConstraint("reason IN ('change', 'heartbeat', 'error')", name=op.f('ck_inbound_raw_raw_reason')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_inbound_raw_account_id_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_raw'))
    )
    with op.batch_alter_table('inbound_raw', schema=None) as batch_op:
        batch_op.create_index('ix_inbound_raw_account_received', ['account_id', 'received_at'], unique=False)

    op.create_table('master_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('position_ticket', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('opened_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price_open', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('sl', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('tp', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('magic', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('absent_count', sa.Integer(), nullable=False),
    sa.Column('absent_since_mono', sa.Numeric(precision=20, scale=6, asdecimal=False), nullable=True),
    sa.Column('absent_epoch', sa.String(length=64), nullable=True),
    sa.Column('mass_episode_id', sa.String(length=64), nullable=True),
    sa.Column('close_source', sa.String(length=24), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("close_source IN ('history', 'absence', 'reversal')", name=op.f('ck_master_positions_close_source')),
    sa.CheckConstraint("state IN ('open', 'closed')", name=op.f('ck_master_positions_master_position_state')),
    sa.CheckConstraint("type IN ('buy', 'sell')", name=op.f('ck_master_positions_position_side')),
    sa.ForeignKeyConstraint(['master_id'], ['accounts.id'], name=op.f('fk_master_positions_master_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_positions')),
    sa.UniqueConstraint('master_id', 'position_id', 'generation', name=op.f('uq_master_positions_master_id_position_id_generation'))
    )
    with op.batch_alter_table('master_positions', schema=None) as batch_op:
        batch_op.create_index('ix_master_positions_master_state', ['master_id', 'state'], unique=False)

    op.create_table('processed_deals',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('deal', sa.BigInteger(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('effect', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("effect IN ('partial', 'reversal', 'close', 'none')", name=op.f('ck_processed_deals_deal_effect')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_processed_deals_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'deal', name=op.f('pk_processed_deals'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('boot_nonce', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_sessions_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_account_retired', ['account_id', 'retired_at'], unique=False)

    op.create_table('symbol_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slave_id', sa.Integer(), nullable=True),
    sa.Column('master_symbol', sa.String(length=64), nullable=False),
    sa.Column('slave_symbol', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['slave_id'], ['accounts.id'], name=op.f('fk_symbol_maps_slave_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbol_maps'))
    )
    with op.batch_alter_table('symbol_maps', schema=None) as batch_op:
        batch_op.create_index('uq_symbol_maps_global_master_symbol', ['master_symbol'], unique=True, sqlite_where=sa.text('slave_id IS NULL'), postgresql_where=sa.text('slave_id IS NULL'))
        batch_op.create_index('uq_symbol_maps_slave_master_symbol', ['slave_id', 'master_symbol'], unique=True, sqlite_where=sa.text('slave_id IS NOT NULL'), postgresql_where=sa.text('slave_id IS NOT NULL'))

    op.create_table('symbol_specs',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('volume_min', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume_step', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume_max', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('contract_size', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('digits', sa.Integer(), nullable=True),
    sa.Column('point', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('trade_mode', sa.String(length=32), nullable=True),
    sa.Column('filling_modes', sa.JSON(), nullable=True),
    sa.Column('stops_level', sa.Integer(), nullable=True),
    sa.Column('freeze_level', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_symbol_specs_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'symbol', name=op.f('pk_symbol_specs'))
    )
    op.create_table('copy_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('slave_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_reason', sa.String(length=255), nullable=True),
    sa.Column('lot_mode', sa.String(length=24), nullable=False),
    sa.Column('lot_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('below_min', sa.String(length=24), nullable=False),
    sa.Column('allow_contract_size_diff', sa.Boolean(), nullable=False),
    sa.Column('magic_mode', sa.String(length=24), nullable=False),
    sa.Column('magic_value', sa.BigInteger(), nullable=True),
    sa.Column('max_slippage_points', sa.Integer(), nullable=True),
    sa.Column('max_entry_deviation_points', sa.Integer(), nullable=True),
    sa.Column('copy_sl_tp', sa.Boolean(), nullable=False),
    sa.CheckConstraint("below_min IN ('skip', 'open_min')", name=op.f('ck_copy_links_below_min')),
    sa.CheckConstraint("lot_mode IN ('master', 'multiplier', 'fixed', 'min_lot_x')", name=op.f('ck_copy_links_lot_mode')),
    sa.CheckConstraint("magic_mode IN ('same', 'fixed')", name=op.f('ck_copy_links_magic_mode')),
    sa.ForeignKeyConstraint(['group_id'], ['copy_groups.id'], name=op.f('fk_copy_links_group_id_copy_groups')),
    sa.ForeignKeyConstraint(['master_id'], ['accounts.id'], name=op.f('fk_copy_links_master_id_accounts')),
    sa.ForeignKeyConstraint(['slave_id'], ['accounts.id'], name=op.f('fk_copy_links_slave_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copy_links')),
    sa.UniqueConstraint('group_id', 'master_id', 'slave_id', name=op.f('uq_copy_links_group_id_master_id_slave_id'))
    )
    with op.batch_alter_table('copy_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copy_links_master_id'), ['master_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copy_links_slave_id'), ['slave_id'], unique=False)

    op.create_table('error_signatures',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('first_raw_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('samples', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_error_signatures_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_raw_id'], ['inbound_raw.id'], name=op.f('fk_error_signatures_first_raw_id_inbound_raw'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('account_id', 'signature', name=op.f('pk_error_signatures'))
    )
    op.create_table('copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('master_position_id', sa.Integer(), nullable=False),
    sa.Column('slave_id', sa.Integer(), nullable=False),
    sa.Column('slave_margin_mode', sa.String(length=24), nullable=False),
    sa.Column('symbol_master', sa.String(length=64), nullable=False),
    sa.Column('symbol_local', sa.String(length=64), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('opened_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('sl', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('tp', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('blocked_by', sa.Integer(), nullable=True),
    sa.Column('skip_reason', sa.String(length=64), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.Column('no_sltp', sa.Boolean(), nullable=False),
    sa.Column('close_intent', sa.Boolean(), nullable=False),
    sa.Column('confirmed_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('reduction_target', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exec_params', sa.JSON(), nullable=True),
    sa.Column('open_order', sa.BigInteger(), nullable=True),
    sa.Column('open_deal', sa.BigInteger(), nullable=True),
    sa.Column('position_ticket', sa.BigInteger(), nullable=True),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('close_deal', sa.BigInteger(), nullable=True),
    sa.Column('price_open', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('price_close', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('profit', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('fee', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('notmodify_count', sa.Integer(), nullable=False),
    sa.Column('notmodify_day', sa.String(length=10), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('slippage_points', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conciliated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("slave_margin_mode IN ('hedging', 'netting')", name=op.f('ck_copies_copy_margin_mode')),
    sa.CheckConstraint("state IN ('pending_blocked', 'pending', 'open', 'cancel_requested', 'closing', 'uncertain', 'closed', 'cancelled', 'skipped', 'error', 'superseded')", name=op.f('ck_copies_copy_state')),
    sa.ForeignKeyConstraint(['blocked_by'], ['copies.id'], name=op.f('fk_copies_blocked_by_copies')),
    sa.ForeignKeyConstraint(['link_id'], ['copy_links.id'], name=op.f('fk_copies_link_id_copy_links')),
    sa.ForeignKeyConstraint(['master_position_id'], ['master_positions.id'], name=op.f('fk_copies_master_position_id_master_positions')),
    sa.ForeignKeyConstraint(['slave_id'], ['accounts.id'], name=op.f('fk_copies_slave_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copies')),
    sa.UniqueConstraint('link_id', 'master_position_id', name=op.f('uq_copies_link_id_master_position_id'))
    )
    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.create_index('ix_copies_slave_state', ['slave_id', 'state'], unique=False)
        batch_op.create_index('uq_copies_hedging_position', ['slave_id', 'position_id'], unique=True, sqlite_where=sa.text("position_id IS NOT NULL AND slave_margin_mode = 'hedging'"), postgresql_where=sa.text("position_id IS NOT NULL AND slave_margin_mode = 'hedging'"))
        batch_op.create_index('uq_copies_netting_slot', ['slave_id', 'symbol_local'], unique=True, sqlite_where=sa.text("slave_margin_mode = 'netting' AND (state IN ('pending','open','cancel_requested','closing','uncertain') OR (state = 'superseded' AND close_intent))"), postgresql_where=sa.text("slave_margin_mode = 'netting' AND (state IN ('pending','open','cancel_requested','closing','uncertain') OR (state = 'superseded' AND close_intent))"))

    op.create_table('commands',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.Column('seq_in_copy', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('attempt_id', sa.String(length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.CheckConstraint("action IN ('open', 'modify', 'close', 'close_partial', 'cancel', 'resolve')", name=op.f('ck_commands_command_action')),
    sa.CheckConstraint("state IN ('queued', 'delivered', 'in_progress', 'retry_wait', 'done', 'failed', 'expired', 'superseded', 'skipped')", name=op.f('ck_commands_command_state')),
    sa.ForeignKeyConstraint(['copy_id'], ['copies.id'], name=op.f('fk_commands_copy_id_copies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commands'))
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index('ix_commands_copy_seq', ['copy_id', 'seq_in_copy'], unique=False)
        batch_op.create_index('ix_commands_state_next', ['state', 'next_attempt_at'], unique=False)

    op.create_table('symbol_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slave_id', sa.Integer(), nullable=False),
    sa.Column('symbol_local', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.CheckConstraint("kind IN ('unexpected_exposure', 'unmanaged_position', 'late_adoption')", name=op.f('ck_symbol_conflicts_conflict_kind')),
    sa.ForeignKeyConstraint(['copy_id'], ['copies.id'], name=op.f('fk_symbol_conflicts_copy_id_copies')),
    sa.ForeignKeyConstraint(['slave_id'], ['accounts.id'], name=op.f('fk_symbol_conflicts_slave_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbol_conflicts'))
    )
    with op.batch_alter_table('symbol_conflicts', schema=None) as batch_op:
        batch_op.create_index('ix_symbol_conflicts_open', ['slave_id', 'symbol_local', 'resolved_at'], unique=False)

    op.create_table('command_attempts',
    sa.Column('command_id', sa.String(length=40), nullable=False),
    sa.Column('attempt_id', sa.String(length=40), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.CheckConstraint("outcome IN ('done', 'done_partial', 'rejected', 'uncertain')", name=op.f('ck_command_attempts_attempt_outcome')),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], name=op.f('fk_command_attempts_command_id_commands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('command_id', 'attempt_id', name=op.f('pk_command_attempts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command_attempts')
    with op.batch_alter_table('symbol_conflicts', schema=None) as batch_op:
        batch_op.drop_index('ix_symbol_conflicts_open')

    op.drop_table('symbol_conflicts')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index('ix_commands_state_next')
        batch_op.drop_index('ix_commands_copy_seq')

    op.drop_table('commands')
    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.drop_index('uq_copies_netting_slot', sqlite_where=sa.text("slave_margin_mode = 'netting' AND (state IN ('pending','open','cancel_requested','closing','uncertain') OR (state = 'superseded' AND close_intent))"), postgresql_where=sa.text("slave_margin_mode = 'netting' AND (state IN ('pending','open','cancel_requested','closing','uncertain') OR (state = 'superseded' AND close_intent))"))
        batch_op.drop_index('uq_copies_hedging_position', sqlite_where=sa.text("position_id IS NOT NULL AND slave_margin_mode = 'hedging'"), postgresql_where=sa.text("position_id IS NOT NULL AND slave_margin_mode = 'hedging'"))
        batch_op.drop_index('ix_copies_slave_state')

    op.drop_table('copies')
    op.drop_table('error_signatures')
    with op.batch_alter_table('copy_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copy_links_slave_id'))
        batch_op.drop_index(batch_op.f('ix_copy_links_master_id'))

    op.drop_table('copy_links')
    op.drop_table('symbol_specs')
    with op.batch_alter_table('symbol_maps', schema=None) as batch_op:
        batch_op.drop_index('uq_symbol_maps_slave_master_symbol', sqlite_where=sa.text('slave_id IS NOT NULL'), postgresql_where=sa.text('slave_id IS NOT NULL'))
        batch_op.drop_index('uq_symbol_maps_global_master_symbol', sqlite_where=sa.text('slave_id IS NULL'), postgresql_where=sa.text('slave_id IS NULL'))

    op.drop_table('symbol_maps')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_account_retired')

    op.drop_table('sessions')
    op.drop_table('processed_deals')
    with op.batch_alter_table('master_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_master_positions_master_state')

    op.drop_table('master_positions')
    with op.batch_alter_table('inbound_raw', schema=None) as batch_op:
        batch_op.drop_index('ix_inbound_raw_account_received')

    op.drop_table('inbound_raw')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_created_at'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('enroll_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enroll_codes_account_id'))

    op.drop_table('enroll_codes')
    with op.batch_alter_table('ea_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_ea_logs_account_received')

    op.drop_table('ea_logs')
    with op.batch_alter_table('copy_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copy_groups_master_id'))

    op.drop_table('copy_groups')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_undelivered')

    op.drop_table('events')
    op.drop_table('api_tokens')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_token_hash'))
        batch_op.drop_index(batch_op.f('ix_accounts_pending_token_hash'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
