"""copies: superseded duplicate siblings outside the (link, master position) unique

A duplicate fill with the same correlation becomes a `superseded` sibling copy of the same
(link, master position) (design 5.8, S52), so the unique constraint becomes a partial unique
index `WHERE state <> 'superseded'`. Generated by autogenerate; checked by hand.
Downgrade fails if superseded siblings exist (delete or re-key them first).

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 18:58:36.617171
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_copies_link_id_master_position_id'), type_='unique')
        batch_op.create_index('uq_copies_link_master_position', ['link_id', 'master_position_id'], unique=True, sqlite_where=sa.text("state <> 'superseded'"), postgresql_where=sa.text("state <> 'superseded'"))


def downgrade() -> None:
    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.drop_index('uq_copies_link_master_position', sqlite_where=sa.text("state <> 'superseded'"), postgresql_where=sa.text("state <> 'superseded'"))
        batch_op.create_unique_constraint(batch_op.f('uq_copies_link_id_master_position_id'), ['link_id', 'master_position_id'])
